# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kahvefaliios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kahvefaliios
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'Firebase/Messaging'
  pod 'Firebase/AdMob'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'Google/SignIn'

  target 'kahvefaliios-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kahvefaliiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kahvefaliios-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kahvefaliios-tvOS


end
