# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kahvefaliios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kahvefaliios
  pod 'Firebase/Messaging'

  target 'kahvefaliios-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kahvefaliiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kahvefaliios-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kahvefaliios-tvOS


end
